# This file is basically created for to store hardcore data of this project at one place
# if environment changes means from SIT(test) to UAT-alpha , UAT-beta changes
# that time whatever hardcoded data we mentioned in this project (email , password , urls)
# also changes . so means you need to change at every place where is required
# so if you have large number of testcases like 500 you need to changes at 100 then
# so you need to changes at 100.
# instead of that time we defined that hardcore(credentials , urls) data in config.ini file
# then we read that data by using python file
# where that credentials and urls present we just called it that methods

# In our project , we have hardcoded data is
# email
# password
# login Url
# registration Url

# on registration page , we generate name , email from faker so it newly create at every time
# so that is not hardcoded



# section
[login data]

email_value = credUser_1447@gmail.com
password_value = credUser_1447


#section
[urls]

login_url = https://automation.credence.in/login
registration_url = https://automation.credence.in/register



[registration_data]
registration_password_value = 'Radheshyam@123'


# No we defined the hardcoded data [credentials , urls]
# but we need to read this data by using python file
# so that's why we create python file for reading data in Utilities python package