# This is the file created for to store hardcoded data at one place
# The reason behind it when environment changes then their url , credentials
# also changes then we need to change that credentials and url
# means change code of  testcases
# so instead of that we define the Url and credentials separately in config file
# so changes makes at once only
# so we define there but we need to read that data which defined
# so that data is read by python file and we call that respective methods at the
# respective locations


# In our project we have some hardcoded data in login page and registration page

# 1.Login Page

# email
# password
# login_url

# 2.Registration Page

# Password
# registration_url




# section
[login_data]

email = credUser_1447@gmail.com
password = redUser_1447


# section
[url]

login_url = https://automation.credence.in/login
registration_url = https://automation.credence.in/register


#section
[registration data]

registration_password = Radheshyam@123



# Now we define all hardcoded data of different pages in config.ini file
# but this data need to reed by pytest so we need to create Readproperties_1.py file
# in utility folder (because its python code so it is in python packages)


